from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os

def generate_pdf_report(project_title, trend_data, top_supplier, filename):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, f"Project Report: {project_title}")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 80, "Generated by Entrepreneur Hub")
    
    # Trend Analysis
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 120, "Market Trend Analysis")
    
    c.setFont("Helvetica", 12)
    y = height - 150
    if trend_data:
        c.drawString(50, y, f"Trend Outlook: {trend_data.get('trend', 'N/A')}")
        c.drawString(50, y - 20, f"Recent Change: {trend_data.get('change_percent', 0)}%")
    else:
         c.drawString(50, y, "No trend data available.")

    # Supplier Recommendation
    c.setFont("Helvetica-Bold", 16)
    y -= 60
    c.drawString(50, y, "Top Recommended Supplier")
    
    c.setFont("Helvetica", 12)
    y -= 30
    if top_supplier:
        s = top_supplier['supplier']
        c.drawString(50, y, f"Name: {s.name}")
        c.drawString(50, y - 20, f"Location: {s.location}")
        c.drawString(50, y - 40, f"Rating: {s.rating}/5.0")
        c.drawString(50, y - 60, f"Est. Total Shipping/Tax: ${top_supplier['total_cost']}")
        c.drawString(50, y - 80, f"Why? Highest score based on quality vs cost.")
    else:
        c.drawString(50, y, "No suppliers found.")
        
    c.save()
    return filename
